In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

In [2]:
dataset = pd.read_csv('admitance.csv')

In [3]:
dataset

SAT Admitted
0    1363       No
1    1792      Yes
2    1954      Yes
3    1653       No
4    1593       No
..    ...      ...
163  1722      Yes
164  1750      Yes
165  1555       No
166  1524       No
167  1461       No

[168 rows x 2 columns]

In [4]:
dataset['Admitted'] = dataset['Admitted'].map({'Yes':1,'No':0})

In [5]:
dataset

SAT  Admitted
0    1363         0
1    1792         1
2    1954         1
3    1653         0
4    1593         0
..    ...       ...
163  1722         1
164  1750         1
165  1555         0
166  1524         0
167  1461         0

[168 rows x 2 columns]

In [6]:
X = dataset['SAT']

In [7]:
X

0      1363
1      1792
2      1954
3      1653
4      1593
       ... 
163    1722
164    1750
165    1555
166    1524
167    1461
Name: SAT, Length: 168, dtype: int64

In [8]:
X = np.array(X)

In [9]:
X = X.reshape(168,1)

In [10]:
X

array([[1363],
       [1792],
       [1954],
       [1653],
       [1593],
       [1755],
       [1775],
       [1887],
       [1893],
       [1580],
       [1857],
       [1880],
       [1664],
       [1364],
       [1693],
       [1850],
       [1633],
       [1634],
       [1636],
       [1855],
       [1987],
       [1997],
       [1422],
       [1508],
       [1720],
       [1879],
       [1634],
       [1802],
       [1849],
       [1764],
       [1460],
       [1675],
       [1656],
       [2020],
       [1850],
       [1865],
       [1664],
       [1872],
       [1654],
       [1393],
       [1587],
       [1631],
       [1931],
       [1370],
       [1810],
       [1414],
       [1761],
       [1477],
       [1486],
       [1561],
       [1549],
       [2050],
       [1697],
       [1543],
       [1934],
       [1385],
       [1670],
       [1735],
       [1634],
       [1777],
       [1550],
       [1715],
       [1925],
       [1842],
       [1786],
       [1435],
       [13

In [11]:
X.shape

(168, 1)

In [12]:
y = np.array(dataset['Admitted'])

In [13]:
y

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [16]:
X_train.shape

(134, 1)

In [17]:
X_test.shape

(34, 1)

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
model = LogisticRegression()

In [20]:
model.fit(X_train,y_train)

LogisticRegression()

In [21]:
X_test

array([[1933],
       [1670],
       [1430],
       [1550],
       [1775],
       [2050],
       [1887],
       [1755],
       [1473],
       [1502],
       [1934],
       [1494],
       [1850],
       [1531],
       [1794],
       [1414],
       [1855],
       [1550],
       [1557],
       [1843],
       [1824],
       [1769],
       [1956],
       [1524],
       [1385],
       [1832],
       [1634],
       [1773],
       [1487],
       [2020],
       [1893],
       [1481],
       [1508],
       [1872]], dtype=int64)

In [22]:
y_test

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [23]:
y_pred = model.predict(X_test)

In [24]:
y_pred

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [25]:
model.score(X_test,y_test)

0.9411764705882353

In [27]:
# confussion metrix, classification report

In [28]:
from sklearn.metrics import confusion_matrix,classification_report


In [29]:
print(confusion_matrix(y_test,y_pred))

[[14  1]
 [ 1 18]]


In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        15
           1       0.95      0.95      0.95        19

    accuracy                           0.94        34
   macro avg       0.94      0.94      0.94        34
weighted avg       0.94      0.94      0.94        34

